"""Writes CALLAHAN_TOKEN (an env var, never argv or stdin — see
bake-and-build.sh) into GeneratedAuthToken.mc as a compiled Monkey C
constant, replacing the whole file each run."""
import os
import sys

path = sys.argv[1]
# JWTs only ever contain base64url characters and dots — no quotes or
# backslashes — but escape defensively anyway rather than assume that
# never changes upstream.
token = os.environ["CALLAHAN_TOKEN"].strip().replace("\\", "\\\\").replace('"', '\\"')

content = f'''import Toybox.Lang;

// GENERATED by scripts/garmin-watch-token/bake-and-build.sh — do not edit
// by hand, and never commit this file (gitignored). See Config.mc for
// why this is a compiled constant rather than an Application.Property.
module GeneratedAuthToken {{
    const VALUE = "{token}";
}}
'''

with open(path, "w") as f:
    f.write(content)
