"""Writes CALLAHAN_TOKEN (an env var, never argv or stdin — see
bake-and-build.sh) and CALLAHAN_BASE_URL into GeneratedAuthToken.mc as
compiled Monkey C constants, replacing the whole file each run."""
import os
import sys

path = sys.argv[1]
# JWTs only ever contain base64url characters and dots — no quotes or
# backslashes — but escape defensively anyway rather than assume that
# never changes upstream.
def literal(value):
    return value.strip().replace("\\", "\\\\").replace('"', '\\"')


token = literal(os.environ["CALLAHAN_TOKEN"])
base_url = literal(os.environ["CALLAHAN_BASE_URL"])

content = f'''import Toybox.Lang;

// GENERATED by scripts/garmin-watch-token/bake-and-build.sh — do not edit
// by hand, and never commit this file (gitignored). See Config.mc for
// why this is a compiled constant rather than an Application.Property.
module GeneratedAuthToken {{
    const VALUE = "{token}";
    const BASE_URL = "{base_url}";
}}
'''

with open(path, "w") as f:
    f.write(content)
