// <auto-generated />
using System;
using Callahan.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Callahan.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817131859_AddTaperCheckIns")]
    partial class AddTaperCheckIns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Callahan.Api.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GarminActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RunSessionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GarminActivityId")
                        .IsUnique()
                        .HasFilter("[GarminActivityId] IS NOT NULL");

                    b.HasIndex("RunSessionTypeId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Callahan.Api.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Name = "Push-up"
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Name = "Pull-up"
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 7,
                            Category = 2,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            Name = "Lunges"
                        },
                        new
                        {
                            Id = 10,
                            Category = 3,
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            Name = "Trap Bar Deadlift"
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            Name = "Bulgarian Split Squat (DB)"
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            Name = "Single Leg Hamstring Curl"
                        },
                        new
                        {
                            Id = 14,
                            Category = 0,
                            Name = "Incline DB Press"
                        },
                        new
                        {
                            Id = 15,
                            Category = 1,
                            Name = "Cable Row"
                        },
                        new
                        {
                            Id = 16,
                            Category = 0,
                            Name = "DB Lateral Raise"
                        },
                        new
                        {
                            Id = 17,
                            Category = 1,
                            Name = "Cable Face Pull"
                        },
                        new
                        {
                            Id = 18,
                            Category = 2,
                            Name = "Single Leg Standing Calf Raise"
                        },
                        new
                        {
                            Id = 19,
                            Category = 2,
                            Name = "Barbell or Trap Bar Squat"
                        },
                        new
                        {
                            Id = 20,
                            Category = 2,
                            Name = "Single Leg RDL (DB)"
                        },
                        new
                        {
                            Id = 21,
                            Category = 0,
                            Name = "Push Press"
                        },
                        new
                        {
                            Id = 22,
                            Category = 1,
                            Name = "Chin-Ups"
                        },
                        new
                        {
                            Id = 23,
                            Category = 3,
                            Name = "Pallof Press"
                        },
                        new
                        {
                            Id = 24,
                            Category = 2,
                            Name = "Box Jump"
                        },
                        new
                        {
                            Id = 25,
                            Category = 3,
                            Name = "Dead Bug"
                        },
                        new
                        {
                            Id = 26,
                            Category = 3,
                            Name = "Cable Woodchop"
                        },
                        new
                        {
                            Id = 27,
                            Category = 3,
                            Name = "Hanging Knee Raise"
                        },
                        new
                        {
                            Id = 28,
                            Category = 3,
                            Name = "Ab Wheel Rollout"
                        },
                        new
                        {
                            Id = 29,
                            Category = 3,
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = 30,
                            Category = 3,
                            Name = "Side Plank with Reach"
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseMuscleTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseMuscleTargets");
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("ExerciseNotes");
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("Callahan.Api.Models.Finisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetReps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetSets")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Finishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 25,
                            RestSeconds = 60,
                            SortOrder = 1,
                            TargetReps = "8/side",
                            TargetSets = 3
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 26,
                            RestSeconds = 60,
                            SortOrder = 2,
                            TargetReps = "12/side",
                            TargetSets = 3
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 27,
                            RestSeconds = 60,
                            SortOrder = 3,
                            TargetReps = "12",
                            TargetSets = 3
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 28,
                            RestSeconds = 60,
                            SortOrder = 4,
                            TargetReps = "8-10",
                            TargetSets = 3
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 29,
                            RestSeconds = 60,
                            SortOrder = 5,
                            TargetReps = "15",
                            TargetSets = 3
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 30,
                            RestSeconds = 60,
                            SortOrder = 6,
                            TargetReps = "30 secs/side",
                            TargetSets = 3
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("Callahan.Api.Models.RunSessionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RunSessionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "High Speed Intervals",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Speed & Acceleration",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Easy Aerobic Run",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.TaperCheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Motivation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Soreness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaperEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaperEventId", "Date")
                        .IsUnique();

                    b.ToTable("TaperCheckIns");
                });

            modelBuilder.Entity("Callahan.Api.Models.TaperEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaperDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TaperEvents");
                });

            modelBuilder.Entity("Callahan.Api.Models.TaperReminderLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaperEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaperEventId", "Date")
                        .IsUnique();

                    b.ToTable("TaperReminderLogs");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Day A",
                            SortOrder = 1,
                            Subtitle = "Lower & Power"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Day B",
                            SortOrder = 2,
                            Subtitle = "Upper"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Day C",
                            SortOrder = 3,
                            Subtitle = "Full Body Athletic"
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutTemplateExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cue")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetReps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetSets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tempo")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutTemplateExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 11,
                            ExerciseOrder = 1,
                            RestSeconds = 150,
                            TargetReps = "5-6",
                            TargetSets = 4,
                            WorkoutTemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 12,
                            ExerciseOrder = 2,
                            RestSeconds = 150,
                            TargetReps = "8/leg",
                            TargetSets = 3,
                            WorkoutTemplateId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 8,
                            ExerciseOrder = 3,
                            RestSeconds = 90,
                            TargetReps = "10-12",
                            TargetSets = 3,
                            WorkoutTemplateId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 13,
                            ExerciseOrder = 4,
                            RestSeconds = 60,
                            TargetReps = "8-10/leg",
                            TargetSets = 3,
                            WorkoutTemplateId = 1
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 14,
                            ExerciseOrder = 1,
                            RestSeconds = 90,
                            TargetReps = "8",
                            TargetSets = 4,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 5,
                            ExerciseOrder = 2,
                            RestSeconds = 90,
                            TargetReps = "6-8",
                            TargetSets = 4,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 7,
                            ExerciseId = 15,
                            ExerciseOrder = 3,
                            RestSeconds = 90,
                            TargetReps = "10",
                            TargetSets = 3,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 8,
                            ExerciseId = 16,
                            ExerciseOrder = 4,
                            RestSeconds = 60,
                            TargetReps = "12",
                            TargetSets = 3,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 9,
                            ExerciseId = 17,
                            ExerciseOrder = 5,
                            RestSeconds = 60,
                            TargetReps = "15",
                            TargetSets = 3,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 10,
                            ExerciseId = 18,
                            ExerciseOrder = 6,
                            RestSeconds = 60,
                            TargetReps = "15-20/leg",
                            TargetSets = 3,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 11,
                            ExerciseId = 19,
                            ExerciseOrder = 1,
                            RestSeconds = 150,
                            TargetReps = "6-8",
                            TargetSets = 4,
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 12,
                            ExerciseId = 20,
                            ExerciseOrder = 2,
                            RestSeconds = 90,
                            TargetReps = "8/leg",
                            TargetSets = 3,
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 13,
                            ExerciseId = 21,
                            ExerciseOrder = 3,
                            RestSeconds = 150,
                            TargetReps = "6",
                            TargetSets = 3,
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 14,
                            ExerciseId = 22,
                            ExerciseOrder = 4,
                            RestSeconds = 90,
                            TargetReps = "AMRAP",
                            TargetSets = 3,
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 15,
                            ExerciseId = 23,
                            ExerciseOrder = 5,
                            RestSeconds = 60,
                            TargetReps = "12/side",
                            TargetSets = 3,
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 16,
                            ExerciseId = 24,
                            ExerciseOrder = 6,
                            RestSeconds = 105,
                            TargetReps = "5",
                            TargetSets = 3,
                            WorkoutTemplateId = 3
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.Activity", b =>
                {
                    b.HasOne("Callahan.Api.Models.RunSessionType", "RunSessionType")
                        .WithMany()
                        .HasForeignKey("RunSessionTypeId");

                    b.Navigation("RunSessionType");
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseMuscleTarget", b =>
                {
                    b.HasOne("Callahan.Api.Models.Exercise", "Exercise")
                        .WithMany("MuscleTargets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseNote", b =>
                {
                    b.HasOne("Callahan.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Callahan.Api.Models.WorkoutSession", "WorkoutSession")
                        .WithMany()
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseSet", b =>
                {
                    b.HasOne("Callahan.Api.Models.Exercise", "Exercise")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Callahan.Api.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Callahan.Api.Models.Finisher", b =>
                {
                    b.HasOne("Callahan.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Callahan.Api.Models.TaperCheckIn", b =>
                {
                    b.HasOne("Callahan.Api.Models.TaperEvent", "TaperEvent")
                        .WithMany()
                        .HasForeignKey("TaperEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaperEvent");
                });

            modelBuilder.Entity("Callahan.Api.Models.TaperReminderLog", b =>
                {
                    b.HasOne("Callahan.Api.Models.TaperEvent", "TaperEvent")
                        .WithMany()
                        .HasForeignKey("TaperEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaperEvent");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutSession", b =>
                {
                    b.HasOne("Callahan.Api.Models.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutTemplateExercise", b =>
                {
                    b.HasOne("Callahan.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Callahan.Api.Models.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("Callahan.Api.Models.Exercise", b =>
                {
                    b.Navigation("MuscleTargets");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutSession", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutTemplate", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
