// <auto-generated />
using System;
using Callahan.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Callahan.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913041049_AddTargetRepsRange")]
    partial class AddTargetRepsRange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Callahan.Api.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActivitySessionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActivityTrainingLoad")
                        .HasColumnType("REAL");

                    b.Property<double?>("AerobicTrainingEffect")
                        .HasColumnType("REAL");

                    b.Property<int?>("AlternationViolations")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AnaerobicTrainingEffect")
                        .HasColumnType("REAL");

                    b.Property<int?>("AvgHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConeDistanceM")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("REAL");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinalScoreAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinalScoreFor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GarminActivityId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("HighSpeedDistanceM")
                        .HasColumnType("REAL");

                    b.Property<string>("LapClassifierMethod")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LapClassifierVersion")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LivePlayDistanceM")
                        .HasColumnType("REAL");

                    b.Property<int?>("LivePlaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MixedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OffFieldSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OnFieldDistanceM")
                        .HasColumnType("REAL");

                    b.Property<int?>("OnFieldSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OnFieldSpeedThresholdMps")
                        .HasColumnType("REAL");

                    b.Property<int?>("PointsPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrainingEffectLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivitySessionTypeId");

                    b.HasIndex("GarminActivityId")
                        .IsUnique()
                        .HasFilter("[GarminActivityId] IS NOT NULL");

                    b.HasIndex("TournamentId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Callahan.Api.Models.ActivityLap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgSpeedMps")
                        .HasColumnType("REAL");

                    b.Property<double?>("DistanceM")
                        .HasColumnType("REAL");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FieldState")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntensityType")
                        .HasColumnType("TEXT");

                    b.Property<int>("LapIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxSpeedMps")
                        .HasColumnType("REAL");

                    b.Property<double?>("MovingDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("StartTimeGmt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "LapIndex")
                        .IsUnique();

                    b.ToTable("ActivityLaps");
                });

            modelBuilder.Entity("Callahan.Api.Models.ActivitySessionTag", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivitySessionTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivityId", "ActivitySessionTypeId");

                    b.HasIndex("ActivitySessionTypeId");

                    b.ToTable("ActivitySessionTags");
                });

            modelBuilder.Entity("Callahan.Api.Models.ActivitySessionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Family")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ActivitySessionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityType = 0,
                            Family = 0,
                            Name = "High Speed Intervals",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ActivityType = 0,
                            Family = 0,
                            Name = "Speed & Acceleration",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ActivityType = 0,
                            Family = 0,
                            Name = "Easy Aerobic Run",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ActivityType = 1,
                            Family = 2,
                            Name = "Solo",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            ActivityType = 1,
                            Family = 2,
                            Name = "Throws",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 6,
                            ActivityType = 1,
                            Family = 2,
                            Name = "Pod",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 7,
                            ActivityType = 1,
                            Family = 2,
                            Name = "Club Training",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 8,
                            ActivityType = 1,
                            Family = 2,
                            Name = "Game",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 9,
                            ActivityType = 0,
                            Family = 1,
                            Name = "Field 1 - Acceleration & Jump Quality",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 10,
                            ActivityType = 0,
                            Family = 1,
                            Name = "Field 2 - Repeat Effort & COD",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.ActivityTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MedianSpacingSec")
                        .HasColumnType("REAL");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SamplesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartEpochMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .IsUnique();

                    b.ToTable("ActivityTracks");
                });

            modelBuilder.Entity("Callahan.Api.Models.DailyWellness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgStressLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwakeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BodyBatteryHigh")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BodyBatteryLow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeepSleepSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HrvLastNightAvg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HrvStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HrvWeeklyAvg")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LightSleepSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RemSleepSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SleepScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SleepScoreQualifier")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SleepSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrainingReadinessFeedback")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingReadinessLevel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrainingReadinessScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyWellness");
                });

            modelBuilder.Entity("Callahan.Api.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAssisted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPerSide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTimeBased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PerSideDelaySeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(8);

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Bench Press",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Deadlift",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            IsAssisted = true,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Pull-up",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Barbell Row",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Leg Press",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Trap Bar Deadlift",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Bulgarian Split Squat (Barbell)",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Single Leg Hamstring Curl",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 14,
                            Category = 0,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Incline DB Press",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 15,
                            Category = 1,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Cable Row",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 16,
                            Category = 0,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "DB Lateral Raise",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 17,
                            Category = 1,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Cable Face Pull",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 18,
                            Category = 2,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Single Leg Standing Calf Raise",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 19,
                            Category = 2,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Barbell Squat",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 20,
                            Category = 2,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Single Leg RDL (DB)",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 21,
                            Category = 0,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Push Press",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 22,
                            Category = 1,
                            IsAssisted = true,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Chin-Ups",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 23,
                            Category = 3,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Pallof Press",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 24,
                            Category = 2,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Box Jump",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 25,
                            Category = 3,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Dead Bug",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 26,
                            Category = 3,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Cable Woodchop",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 27,
                            Category = 3,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Hanging Knee Raise",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 28,
                            Category = 3,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Ab Wheel Rollout",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 29,
                            Category = 3,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Cable Crunch",
                            PerSideDelaySeconds = 8
                        },
                        new
                        {
                            Id = 30,
                            Category = 3,
                            IsAssisted = false,
                            IsPerSide = false,
                            IsTimeBased = false,
                            Name = "Side Plank with Reach",
                            PerSideDelaySeconds = 8
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseMuscleTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseMuscleTargets");
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("ExerciseNotes");
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId", "ExerciseId", "SetOrder")
                        .IsUnique();

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("Callahan.Api.Models.Finisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetReps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetSets")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Finishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 25,
                            RestSeconds = 60,
                            SortOrder = 1,
                            TargetReps = "8/side",
                            TargetSets = 3
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 26,
                            RestSeconds = 60,
                            SortOrder = 2,
                            TargetReps = "12/side",
                            TargetSets = 3
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 27,
                            RestSeconds = 60,
                            SortOrder = 3,
                            TargetReps = "12",
                            TargetSets = 3
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 28,
                            RestSeconds = 60,
                            SortOrder = 4,
                            TargetReps = "8-10",
                            TargetSets = 3
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 29,
                            RestSeconds = 60,
                            SortOrder = 5,
                            TargetReps = "15",
                            TargetSets = 3
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 30,
                            RestSeconds = 60,
                            SortOrder = 6,
                            TargetReps = "30 secs/side",
                            TargetSets = 3
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.MonthlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyReports");
                });

            modelBuilder.Entity("Callahan.Api.Models.PlanSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActivitySessionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoutineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivitySessionTypeId");

                    b.HasIndex("RoutineId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("PlanSlots");
                });

            modelBuilder.Entity("Callahan.Api.Models.PlanSlotWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanSlotId", "WeekStart")
                        .IsUnique();

                    b.ToTable("PlanSlotWeeks");
                });

            modelBuilder.Entity("Callahan.Api.Models.PlateCalcSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("PlateCalcSettings");
                });

            modelBuilder.Entity("Callahan.Api.Models.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("Callahan.Api.Models.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Routines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cadence = "Every day, including rest days. Five minutes.",
                            Name = "Daily Ankle Circuit",
                            Notes = "This is not an accessory block. Three years of recurrence with no structural diagnosis; the working assumption is functional instability, which responds to proprioceptive and balance work. Highest value, lowest cost thing in the program.\n\nProgression ladder - move up when the current level feels easy, roughly every 2-3 weeks:\n- Eyes open, firm ground\n- Eyes closed, firm ground\n- Unstable surface (pillow, folded mat)\n- Unstable surface + ball toss against a wall\n- Single-leg hop and stick, multi-directional\n\nKeep the braces for games and pod sessions. Braces and neuromuscular work are complementary, not alternatives.",
                            Purpose = "Proprioceptive work for the ankle - the foundation of the program",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Cadence = "2x weekly, 15 mins - before Gym 1 and Gym 3",
                            Name = "Jump Block",
                            Notes = "Not a gym session. These need overhead space, a run-up, or somewhere you can land hard, which a commercial gym floor isn't. Do them at home, in a driveway, a park, or anywhere with a basketball ring, then head to the gym. Pogos and skater bounds stay in the gym - they're low, quiet and nobody looks twice.\n\nIntroduce it over 3 weeks, not in one go:\n- Week 1: CMJ 2x3 only. No depth drops.\n- Week 2: CMJ 3x3 + depth drops 2x3 from a low step.\n- Week 3: full prescription.\n- Progress depth-drop height only after 4 weeks of clean, silent landings.\n\nOne-leg approach jumps stay in Field 1, where they already are. They need a real run-up and a high target, and Field 1 is the only place you're genuinely fresh. Don't add them here as well - one-leg landing volume is the thing you least want to spike with a three-year ankle history.\n\nThe adherence risk: a 15-minute thing that happens before you leave the house is the easiest thing in this program to skip. Tie it to leaving, not to a time.",
                            Purpose = "Vertical work - the number one priority, kept out of the gym",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.RoutineCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoutineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId", "Date")
                        .IsUnique();

                    b.ToTable("RoutineCompletions");
                });

            modelBuilder.Entity("Callahan.Api.Models.RoutineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cue")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoutineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("RoutineItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemOrder = 1,
                            Name = "Single-leg balance, eyes open",
                            Prescription = "45 secs/side",
                            RoutineId = 1
                        },
                        new
                        {
                            Id = 2,
                            ItemOrder = 2,
                            Name = "Single-leg balance, eyes closed",
                            Prescription = "30 secs/side",
                            RoutineId = 1
                        },
                        new
                        {
                            Id = 3,
                            ItemOrder = 3,
                            Name = "Single-leg balance + head turns",
                            Prescription = "20 secs/side",
                            RoutineId = 1
                        },
                        new
                        {
                            Id = 4,
                            ItemOrder = 4,
                            Name = "Banded ankle eversion",
                            Prescription = "15/side",
                            RoutineId = 1
                        },
                        new
                        {
                            Id = 5,
                            ItemOrder = 5,
                            Name = "Tibialis raises",
                            Prescription = "20",
                            RoutineId = 1
                        },
                        new
                        {
                            Id = 6,
                            ItemOrder = 6,
                            Name = "Single-leg calf raise, slow",
                            Prescription = "12/side",
                            RoutineId = 1
                        },
                        new
                        {
                            Id = 7,
                            Cue = "Balance + calf raise. Warm the ankle before you land on it.",
                            ItemOrder = 1,
                            Name = "Ankle circuit (abbreviated)",
                            Prescription = "",
                            RoutineId = 2
                        },
                        new
                        {
                            Id = 8,
                            Cue = "Warm-up, low",
                            ItemOrder = 2,
                            Name = "Pogo hops",
                            Prescription = "2x10",
                            RoutineId = 2
                        },
                        new
                        {
                            Id = 9,
                            Cue = "Measure weekly. Mark a fixed point - a wall, a doorframe, a ring. Full recovery.",
                            ItemOrder = 3,
                            Name = "Countermovement jump to target",
                            Prescription = "4x3",
                            RoutineId = 2
                        },
                        new
                        {
                            Id = 10,
                            Cue = "A low step to start (~30cm). Absorb, freeze, hold 2 secs.",
                            ItemOrder = 4,
                            Name = "Depth drop to stick landing",
                            Prescription = "3x5",
                            RoutineId = 2
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetTournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartDate");

                    b.HasIndex("TargetTournamentId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Callahan.Api.Models.TaperCheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Motivation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Soreness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Date")
                        .IsUnique();

                    b.ToTable("TaperCheckIns");
                });

            modelBuilder.Entity("Callahan.Api.Models.TaperReminderLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Date")
                        .IsUnique();

                    b.ToTable("TaperReminderLogs");
                });

            modelBuilder.Entity("Callahan.Api.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("PlannedReductionPercent")
                        .HasColumnType("REAL");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaperDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("StartDate");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Callahan.Api.Models.UsageEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<int>("BackendUptimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DwellMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsageEvents");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowerBodyLoad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsRetired = false,
                            LowerBodyLoad = 0,
                            Name = "Day A",
                            PriorityOrder = 0,
                            SortOrder = 1,
                            Subtitle = "Lower & Power"
                        },
                        new
                        {
                            Id = 2,
                            IsRetired = false,
                            LowerBodyLoad = 0,
                            Name = "Day B",
                            PriorityOrder = 0,
                            SortOrder = 2,
                            Subtitle = "Upper"
                        },
                        new
                        {
                            Id = 3,
                            IsRetired = false,
                            LowerBodyLoad = 0,
                            Name = "Day C",
                            PriorityOrder = 0,
                            SortOrder = 3,
                            Subtitle = "Full Body Athletic"
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutTemplateExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cue")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupersetWithNext")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetReps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetRepsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetRepsMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tempo")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarmupSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutTemplateExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 11,
                            ExerciseOrder = 1,
                            RestSeconds = 150,
                            SupersetWithNext = false,
                            TargetReps = "5-6",
                            TargetSets = 4,
                            WarmupSets = 1,
                            WorkoutTemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 12,
                            ExerciseOrder = 2,
                            RestSeconds = 150,
                            SupersetWithNext = false,
                            TargetReps = "8/leg",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 8,
                            ExerciseOrder = 3,
                            RestSeconds = 90,
                            SupersetWithNext = false,
                            TargetReps = "10-12",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 13,
                            ExerciseOrder = 4,
                            RestSeconds = 60,
                            SupersetWithNext = false,
                            TargetReps = "8-10/leg",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 1
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 14,
                            ExerciseOrder = 1,
                            RestSeconds = 90,
                            SupersetWithNext = false,
                            TargetReps = "8",
                            TargetSets = 4,
                            WarmupSets = 1,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 5,
                            ExerciseOrder = 2,
                            RestSeconds = 90,
                            SupersetWithNext = false,
                            TargetReps = "6-8",
                            TargetSets = 4,
                            WarmupSets = 0,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 7,
                            ExerciseId = 15,
                            ExerciseOrder = 3,
                            RestSeconds = 90,
                            SupersetWithNext = false,
                            TargetReps = "10",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 8,
                            ExerciseId = 16,
                            ExerciseOrder = 4,
                            RestSeconds = 60,
                            SupersetWithNext = false,
                            TargetReps = "12",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 9,
                            ExerciseId = 17,
                            ExerciseOrder = 5,
                            RestSeconds = 60,
                            SupersetWithNext = false,
                            TargetReps = "15",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 10,
                            ExerciseId = 18,
                            ExerciseOrder = 6,
                            RestSeconds = 60,
                            SupersetWithNext = false,
                            TargetReps = "15-20/leg",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 11,
                            ExerciseId = 19,
                            ExerciseOrder = 1,
                            RestSeconds = 150,
                            SupersetWithNext = false,
                            TargetReps = "6-8",
                            TargetSets = 4,
                            WarmupSets = 1,
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 12,
                            ExerciseId = 20,
                            ExerciseOrder = 2,
                            RestSeconds = 90,
                            SupersetWithNext = false,
                            TargetReps = "8/leg",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 13,
                            ExerciseId = 21,
                            ExerciseOrder = 3,
                            RestSeconds = 150,
                            SupersetWithNext = false,
                            TargetReps = "6",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 14,
                            ExerciseId = 22,
                            ExerciseOrder = 4,
                            RestSeconds = 90,
                            SupersetWithNext = false,
                            TargetReps = "AMRAP",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 15,
                            ExerciseId = 23,
                            ExerciseOrder = 5,
                            RestSeconds = 60,
                            SupersetWithNext = false,
                            TargetReps = "12/side",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 16,
                            ExerciseId = 24,
                            ExerciseOrder = 6,
                            RestSeconds = 105,
                            SupersetWithNext = false,
                            TargetReps = "5",
                            TargetSets = 3,
                            WarmupSets = 0,
                            WorkoutTemplateId = 3
                        });
                });

            modelBuilder.Entity("Callahan.Api.Models.Activity", b =>
                {
                    b.HasOne("Callahan.Api.Models.ActivitySessionType", "ActivitySessionType")
                        .WithMany()
                        .HasForeignKey("ActivitySessionTypeId");

                    b.HasOne("Callahan.Api.Models.Tournament", "Tournament")
                        .WithMany("Activities")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivitySessionType");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Callahan.Api.Models.ActivityLap", b =>
                {
                    b.HasOne("Callahan.Api.Models.Activity", "Activity")
                        .WithMany("Laps")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Callahan.Api.Models.ActivitySessionTag", b =>
                {
                    b.HasOne("Callahan.Api.Models.Activity", "Activity")
                        .WithMany("SessionTags")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Callahan.Api.Models.ActivitySessionType", "SessionType")
                        .WithMany()
                        .HasForeignKey("ActivitySessionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("SessionType");
                });

            modelBuilder.Entity("Callahan.Api.Models.ActivityTrack", b =>
                {
                    b.HasOne("Callahan.Api.Models.Activity", "Activity")
                        .WithOne("Track")
                        .HasForeignKey("Callahan.Api.Models.ActivityTrack", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseMuscleTarget", b =>
                {
                    b.HasOne("Callahan.Api.Models.Exercise", "Exercise")
                        .WithMany("MuscleTargets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseNote", b =>
                {
                    b.HasOne("Callahan.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Callahan.Api.Models.WorkoutSession", "WorkoutSession")
                        .WithMany()
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Callahan.Api.Models.ExerciseSet", b =>
                {
                    b.HasOne("Callahan.Api.Models.Exercise", "Exercise")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Callahan.Api.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Callahan.Api.Models.Finisher", b =>
                {
                    b.HasOne("Callahan.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Callahan.Api.Models.PlanSlot", b =>
                {
                    b.HasOne("Callahan.Api.Models.ActivitySessionType", "ActivitySessionType")
                        .WithMany()
                        .HasForeignKey("ActivitySessionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Callahan.Api.Models.Routine", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Callahan.Api.Models.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActivitySessionType");

                    b.Navigation("Routine");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("Callahan.Api.Models.PlanSlotWeek", b =>
                {
                    b.HasOne("Callahan.Api.Models.PlanSlot", "PlanSlot")
                        .WithMany("Weeks")
                        .HasForeignKey("PlanSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanSlot");
                });

            modelBuilder.Entity("Callahan.Api.Models.RoutineCompletion", b =>
                {
                    b.HasOne("Callahan.Api.Models.Routine", "Routine")
                        .WithMany("Completions")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("Callahan.Api.Models.RoutineItem", b =>
                {
                    b.HasOne("Callahan.Api.Models.Routine", "Routine")
                        .WithMany("Items")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("Callahan.Api.Models.Season", b =>
                {
                    b.HasOne("Callahan.Api.Models.Tournament", "TargetTournament")
                        .WithMany()
                        .HasForeignKey("TargetTournamentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TargetTournament");
                });

            modelBuilder.Entity("Callahan.Api.Models.TaperCheckIn", b =>
                {
                    b.HasOne("Callahan.Api.Models.Tournament", "Tournament")
                        .WithMany("TaperCheckIns")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Callahan.Api.Models.TaperReminderLog", b =>
                {
                    b.HasOne("Callahan.Api.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Callahan.Api.Models.Tournament", b =>
                {
                    b.HasOne("Callahan.Api.Models.Season", "Season")
                        .WithMany("Tournaments")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutSession", b =>
                {
                    b.HasOne("Callahan.Api.Models.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutTemplateExercise", b =>
                {
                    b.HasOne("Callahan.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Callahan.Api.Models.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("Callahan.Api.Models.Activity", b =>
                {
                    b.Navigation("Laps");

                    b.Navigation("SessionTags");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Callahan.Api.Models.Exercise", b =>
                {
                    b.Navigation("MuscleTargets");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Callahan.Api.Models.PlanSlot", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("Callahan.Api.Models.Routine", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Callahan.Api.Models.Season", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("Callahan.Api.Models.Tournament", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("TaperCheckIns");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutSession", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Callahan.Api.Models.WorkoutTemplate", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
