import Toybox.Application;
import Toybox.Lang;

// Base URL is a real Property (rarely changes, fine to edit via Garmin
// Connect Mobile if that path is ever reachable). The auth token is NOT a
// Property, deliberately — Connect IQ properties persist across app
// updates by design (same app id keeps its old value even after a
// rebuild with a different default), which is exactly wrong for a token
// that needs refreshing monthly. GeneratedAuthToken.mc is regenerated by
// scripts/garmin-watch-token/bake-and-build.sh on every run and compiled
// in as a plain constant, so every rebuild fully replaces it with no
// carryover. See README.md in that script's directory.
class Config {

    function getBaseUrl() as String {
        var url = Application.Properties.getValue("BaseUrl") as String?;
        return url != null ? url : "";
    }

    function getAuthToken() as String {
        return GeneratedAuthToken.VALUE;
    }

    function isConfigured() as Boolean {
        return getBaseUrl().length() > 0 && getAuthToken().length() > 0;
    }
}
