import Toybox.Lang;

// Neither value is an Application.Property, deliberately: Connect IQ
// properties persist across app updates by design (same app id keeps its
// old value even after a rebuild with a different default), and a
// sideloaded data field has no settings screen to change one anyway.
// GeneratedAuthToken.mc is regenerated by
// scripts/garmin-watch-token/bake-and-build.sh on every run and compiled
// in as plain constants, so every rebuild fully replaces them with no
// carryover. See README.md in that script's directory.
class Config {

    function getBaseUrl() as String {
        return GeneratedAuthToken.BASE_URL;
    }

    function getAuthToken() as String {
        return GeneratedAuthToken.VALUE;
    }

    function isConfigured() as Boolean {
        return getBaseUrl().length() > 0 && getAuthToken().length() > 0;
    }
}
